export const SIGN_IN = "SIGN_IN";

export const SIGN_OUT = "SIGN_OUT";

export const GET_USER = "GET_USER";

export const GET_CONVERSATION_LIST = "GET_CONVERSATION_LIST";

export const SELECTED_CONVERSATION = "SELECTED_CONVERSATION";

export const CREATE_NEW_CONVERSATION = "CREATE_NEW_CONVERSATION";

export const GET_MESSAGE_LIST = "GET_MESSAGE_LIST";

export const LOAD_MORE_MESSAGE = "LOAD_MORE_MESSAGE";

export const NEW_MESSAGE = "NEW_MESSAGE";

export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const START_CALLING = "START_CALLING";

export const SET_CURRENT_TAB = "SET_CURRENT_TAB";